app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:123456aaa@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenConns: 114

redis:
  addr: localhost:6379
  DB: 0
  Password: ""